import 'package:flutter/material.dart';

import 'app_palette.dart';

/// Every theme the user can pick from Settings › Select Theme.
///
/// The family is amber / orange — the original app's blue is gone entirely —
/// with both dark and light members so the picker feels complete. Add a new
/// entry here and it appears in the theme screen automatically.
///
/// Colour notes for this revision:
///   * backgrounds sit deeper so surfaces read as lifted panels,
///   * `outline` is kept close to `surface` on purpose — the UI no longer
///     draws hairline rules, so outline is only a whisper of separation,
///   * `textSecondary` was lightened for readability on small labels,
///   * keypad faces are distinct from `surface` so the keypad reads as a
///     keypad rather than as part of the page.
class ThemeCatalog {
  const ThemeCatalog._();

  static const String defaultId = 'sydney_coral';

  static const List<AppPalette> all = <AppPalette>[
    // ---------------------------------------------------------- light ----
    AppPalette(
      id: 'paper_white',
      name: 'Paper White',
      city: 'Default',
      brightness: Brightness.light,
      primary: Color(0xFFFF7A00),
      onPrimary: Color(0xFFFFFFFF),
      accent: Color(0xFF2F80ED),
      background: Color(0xFFFFFFFF),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFF4F6FB),
      outline: Color(0xFFE6EAF2),
      textPrimary: Color(0xFF1A1D26),
      textSecondary: Color(0xFF5C6475),
      keyFace: Color(0xFFFFFFFF),
      keyFaceAlt: Color(0xFFEEF2FF),
      keyText: Color(0xFF1A1D26),
      equalsKey: Color(0xFFE53935),
      up: Color(0xFF2E7D32),
      down: Color(0xFFE53935),
    ),
    // ----------------------------------------------------------- dark ----
    AppPalette(
      id: 'amber_night',
      name: 'Amber Night',
      city: 'Night',
      brightness: Brightness.dark,
      primary: Color(0xFFFFB627),
      onPrimary: Color(0xFF1A1103),
      accent: Color(0xFFFF8F3F),
      background: Color(0xFF0B0D11),
      surface: Color(0xFF14171D),
      surfaceAlt: Color(0xFF1C212A),
      outline: Color(0xFF232A35),
      textPrimary: Color(0xFFF4F6FA),
      textSecondary: Color(0xFFA0A9B8),
      keyFace: Color(0xFF171B22),
      keyFaceAlt: Color(0xFF212731),
      keyText: Color(0xFFF4F6FA),
      equalsKey: Color(0xFFF04438),
      up: Color(0xFF32D583),
      down: Color(0xFFF04438),
    ),
    AppPalette(
      id: 'dubai_gold',
      name: 'Desert Gold',
      city: 'Dubai',
      brightness: Brightness.dark,
      primary: Color(0xFFEFC569),
      onPrimary: Color(0xFF221903),
      accent: Color(0xFFD9A441),
      background: Color(0xFF100E09),
      surface: Color(0xFF1A1710),
      surfaceAlt: Color(0xFF242017),
      outline: Color(0xFF2E2920),
      textPrimary: Color(0xFFF8F3E6),
      textSecondary: Color(0xFFB5AB93),
      keyFace: Color(0xFF1D1A13),
      keyFaceAlt: Color(0xFF27221A),
      keyText: Color(0xFFF8F3E6),
      equalsKey: Color(0xFFCF5238),
      up: Color(0xFF6BC894),
      down: Color(0xFFCF5238),
    ),
    AppPalette(
      id: 'marrakesh_saffron',
      name: 'Saffron Souk',
      city: 'Marrakesh',
      brightness: Brightness.dark,
      primary: Color(0xFFF5A44A),
      onPrimary: Color(0xFF2A1604),
      accent: Color(0xFFE87548),
      background: Color(0xFF120F0E),
      surface: Color(0xFF1C1817),
      surfaceAlt: Color(0xFF26201E),
      outline: Color(0xFF322A27),
      textPrimary: Color(0xFFF8F1EA),
      textSecondary: Color(0xFFB7A59D),
      keyFace: Color(0xFF1F1A19),
      keyFaceAlt: Color(0xFF2A2321),
      keyText: Color(0xFFF8F1EA),
      equalsKey: Color(0xFFDC4A33),
      up: Color(0xFF4FC08A),
      down: Color(0xFFDC4A33),
    ),
    AppPalette(
      id: 'tokyo_tangerine',
      name: 'Neon Tangerine',
      city: 'Tokyo',
      brightness: Brightness.dark,
      primary: Color(0xFFFF8226),
      onPrimary: Color(0xFF190C02),
      accent: Color(0xFFFFD166),
      background: Color(0xFF090B0E),
      surface: Color(0xFF111419),
      surfaceAlt: Color(0xFF191E25),
      outline: Color(0xFF222831),
      textPrimary: Color(0xFFF0F3F7),
      textSecondary: Color(0xFF939CAB),
      keyFace: Color(0xFF14181E),
      keyFaceAlt: Color(0xFF1E242C),
      keyText: Color(0xFFF0F3F7),
      equalsKey: Color(0xFFFF4D4D),
      up: Color(0xFF32D583),
      down: Color(0xFFFF4D4D),
    ),
    AppPalette(
      id: 'seoul_sunset',
      name: 'Sunset Coral',
      city: 'Seoul',
      brightness: Brightness.dark,
      primary: Color(0xFFFF7454),
      onPrimary: Color(0xFF1F0904),
      accent: Color(0xFFFFA878),
      background: Color(0xFF0E0E11),
      surface: Color(0xFF17181D),
      surfaceAlt: Color(0xFF202128),
      outline: Color(0xFF292B33),
      textPrimary: Color(0xFFF4F4F8),
      textSecondary: Color(0xFF9FA0AB),
      keyFace: Color(0xFF1A1B21),
      keyFaceAlt: Color(0xFF24262E),
      keyText: Color(0xFFF4F4F8),
      equalsKey: Color(0xFFE8483F),
      up: Color(0xFF38CF8B),
      down: Color(0xFFE8483F),
    ),
    AppPalette(
      id: 'oslo_copper',
      name: 'Copper Dawn',
      city: 'Oslo',
      brightness: Brightness.dark,
      primary: Color(0xFFD2834F),
      onPrimary: Color(0xFF1A0E06),
      accent: Color(0xFFE5A972),
      background: Color(0xFF0D0F11),
      surface: Color(0xFF161A1D),
      surfaceAlt: Color(0xFF1F2429),
      outline: Color(0xFF272D33),
      textPrimary: Color(0xFFEEF1F3),
      textSecondary: Color(0xFF9AA1A9),
      keyFace: Color(0xFF191D21),
      keyFaceAlt: Color(0xFF232830),
      keyText: Color(0xFFEEF1F3),
      equalsKey: Color(0xFFC24A31),
      up: Color(0xFF52BE8A),
      down: Color(0xFFC24A31),
    ),
    AppPalette(
      id: 'cairo_bronze',
      name: 'Bronze Bazaar',
      city: 'Cairo',
      brightness: Brightness.dark,
      primary: Color(0xFFC28F3F),
      onPrimary: Color(0xFF1B1304),
      accent: Color(0xFFDDBA74),
      background: Color(0xFF100F0D),
      surface: Color(0xFF191816),
      surfaceAlt: Color(0xFF22211D),
      outline: Color(0xFF2B2A25),
      textPrimary: Color(0xFFF2EFE8),
      textSecondary: Color(0xFFA8A395),
      keyFace: Color(0xFF1C1B18),
      keyFaceAlt: Color(0xFF26241F),
      keyText: Color(0xFFF2EFE8),
      equalsKey: Color(0xFFB34430),
      up: Color(0xFF5BB683),
      down: Color(0xFFB34430),
    ),

    // ---------------------------------------------------------- light ----
    AppPalette(
      id: 'lisbon_terracotta',
      name: 'Terracotta',
      city: 'Lisbon',
      brightness: Brightness.light,
      primary: Color(0xFFC1552E),
      onPrimary: Color(0xFFFFFFFF),
      accent: Color(0xFFE08A3C),
      background: Color(0xFFFFF7F1),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFF8EFE7),
      outline: Color(0xFFEEE0D5),
      textPrimary: Color(0xFF241A14),
      textSecondary: Color(0xFF857366),
      keyFace: Color(0xFFFFFFFF),
      keyFaceAlt: Color(0xFFF5E9DF),
      keyText: Color(0xFF241A14),
      equalsKey: Color(0xFFC1552E),
      up: Color(0xFF17915A),
      down: Color(0xFFC2392C),
    ),
    AppPalette(
      id: 'zurich_honey',
      name: 'Honey Light',
      city: 'Zürich',
      brightness: Brightness.light,
      primary: Color(0xFFDE9A12),
      onPrimary: Color(0xFF221500),
      accent: Color(0xFFF5C451),
      background: Color(0xFFFFFCF5),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFFAF4E7),
      outline: Color(0xFFF0E7D5),
      textPrimary: Color(0xFF1F1B12),
      textSecondary: Color(0xFF7C7464),
      keyFace: Color(0xFFFFFFFF),
      keyFaceAlt: Color(0xFFF6EFDF),
      keyText: Color(0xFF1F1B12),
      equalsKey: Color(0xFFD9541F),
      up: Color(0xFF17915A),
      down: Color(0xFFD03A30),
    ),
    AppPalette(
      id: 'sydney_coral',
      name: 'Coral Bay',
      city: 'Sydney',
      brightness: Brightness.light,
      primary: Color(0xFFF0603A),
      onPrimary: Color(0xFFFFFFFF),
      accent: Color(0xFFFFA26B),
      background: Color(0xFFFFF7F4),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFFDEDE7),
      outline: Color(0xFFF7DDD3),
      textPrimary: Color(0xFF231714),
      textSecondary: Color(0xFF85706A),
      keyFace: Color(0xFFFFFFFF),
      keyFaceAlt: Color(0xFFFAE7DE),
      keyText: Color(0xFF231714),
      equalsKey: Color(0xFFE04236),
      up: Color(0xFF17915A),
      down: Color(0xFFE04236),
    ),
  ];

  static AppPalette byId(String? id) {
    return all.firstWhere(
      (AppPalette p) => p.id == id,
      orElse: () => all.firstWhere((AppPalette p) => p.id == defaultId),
    );
  }
}
