// GENERATED FILE — unit conversion tables for CurrencyPro.
//
//   toBase(v)   = reciprocal ? factor / v : v * factor + offset
//   fromBase(b) = reciprocal ? factor / b : (b - offset) / factor

import 'package:flutter/material.dart';

import 'unit_models.dart';

/// All measurement categories offered by the Unit Converter hub.
final List<UnitCategory> kUnitCategories = <UnitCategory>[
  UnitCategory(
    id: 'length',
    name: 'Length',
    icon: Icons.straighten,
    baseUnitLabel: 'metre',
    units: <Unit>[
      Unit(name: 'Nanometre', symbol: 'nm', factor: 1e-09, offset: 0.0, reciprocal: false),
      Unit(name: 'Micrometre', symbol: 'µm', factor: 1e-06, offset: 0.0, reciprocal: false),
      Unit(name: 'Millimetre', symbol: 'mm', factor: 0.001, offset: 0.0, reciprocal: false),
      Unit(name: 'Centimetre', symbol: 'cm', factor: 0.01, offset: 0.0, reciprocal: false),
      Unit(name: 'Decimetre', symbol: 'dm', factor: 0.1, offset: 0.0, reciprocal: false),
      Unit(name: 'Metre', symbol: 'm', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilometre', symbol: 'km', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Inch', symbol: 'in', factor: 0.0254, offset: 0.0, reciprocal: false),
      Unit(name: 'Foot', symbol: 'ft', factor: 0.3048, offset: 0.0, reciprocal: false),
      Unit(name: 'Yard', symbol: 'yd', factor: 0.9144, offset: 0.0, reciprocal: false),
      Unit(name: 'Mile', symbol: 'mi', factor: 1609.344, offset: 0.0, reciprocal: false),
      Unit(name: 'Nautical mile', symbol: 'nmi', factor: 1852.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Furlong', symbol: 'fur', factor: 201.168, offset: 0.0, reciprocal: false),
      Unit(name: 'Chain', symbol: 'ch', factor: 20.1168, offset: 0.0, reciprocal: false),
      Unit(name: 'Fathom', symbol: 'ftm', factor: 1.8288, offset: 0.0, reciprocal: false),
      Unit(name: 'Hand', symbol: 'hh', factor: 0.1016, offset: 0.0, reciprocal: false),
      Unit(name: 'Light year', symbol: 'ly', factor: 9460730472580800.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Astronomical unit', symbol: 'AU', factor: 149597870700.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Parsec', symbol: 'pc', factor: 3.085677581491367e+16, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'mass',
    name: 'Weight & Mass',
    icon: Icons.monitor_weight_outlined,
    baseUnitLabel: 'kilogram',
    units: <Unit>[
      Unit(name: 'Microgram', symbol: 'µg', factor: 1e-09, offset: 0.0, reciprocal: false),
      Unit(name: 'Milligram', symbol: 'mg', factor: 1e-06, offset: 0.0, reciprocal: false),
      Unit(name: 'Gram', symbol: 'g', factor: 0.001, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilogram', symbol: 'kg', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Metric tonne', symbol: 't', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Carat', symbol: 'ct', factor: 0.0002, offset: 0.0, reciprocal: false),
      Unit(name: 'Ounce', symbol: 'oz', factor: 0.028349523125, offset: 0.0, reciprocal: false),
      Unit(name: 'Troy ounce', symbol: 'oz t', factor: 0.0311034768, offset: 0.0, reciprocal: false),
      Unit(name: 'Pound', symbol: 'lb', factor: 0.45359237, offset: 0.0, reciprocal: false),
      Unit(name: 'Stone', symbol: 'st', factor: 6.35029318, offset: 0.0, reciprocal: false),
      Unit(name: 'US ton (short)', symbol: 'ton', factor: 907.18474, offset: 0.0, reciprocal: false),
      Unit(name: 'UK ton (long)', symbol: 'long tn', factor: 1016.0469088, offset: 0.0, reciprocal: false),
      Unit(name: 'Grain', symbol: 'gr', factor: 6.479891e-05, offset: 0.0, reciprocal: false),
      Unit(name: 'Slug', symbol: 'slug', factor: 14.5939029372, offset: 0.0, reciprocal: false),
      Unit(name: 'Tola', symbol: 'tola', factor: 0.01166, offset: 0.0, reciprocal: false),
      Unit(name: 'Bhori / Vori', symbol: 'bhori', factor: 0.0116638, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'temperature',
    name: 'Temperature',
    icon: Icons.thermostat,
    baseUnitLabel: 'kelvin',
    units: <Unit>[
      Unit(name: 'Celsius', symbol: '°C', factor: 1.0, offset: 273.15, reciprocal: false),
      Unit(name: 'Fahrenheit', symbol: '°F', factor: 0.5555555555555556, offset: 255.3722222222222, reciprocal: false),
      Unit(name: 'Kelvin', symbol: 'K', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Rankine', symbol: '°R', factor: 0.5555555555555556, offset: 0.0, reciprocal: false),
      Unit(name: 'Réaumur', symbol: '°Ré', factor: 1.25, offset: 273.15, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'area',
    name: 'Area',
    icon: Icons.crop_square,
    baseUnitLabel: 'square metre',
    units: <Unit>[
      Unit(name: 'Square millimetre', symbol: 'mm²', factor: 1e-06, offset: 0.0, reciprocal: false),
      Unit(name: 'Square centimetre', symbol: 'cm²', factor: 0.0001, offset: 0.0, reciprocal: false),
      Unit(name: 'Square metre', symbol: 'm²', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Square kilometre', symbol: 'km²', factor: 1000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Hectare', symbol: 'ha', factor: 10000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Are', symbol: 'a', factor: 100.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Square inch', symbol: 'in²', factor: 0.00064516, offset: 0.0, reciprocal: false),
      Unit(name: 'Square foot', symbol: 'ft²', factor: 0.09290304, offset: 0.0, reciprocal: false),
      Unit(name: 'Square yard', symbol: 'yd²', factor: 0.83612736, offset: 0.0, reciprocal: false),
      Unit(name: 'Acre', symbol: 'ac', factor: 4046.8564224, offset: 0.0, reciprocal: false),
      Unit(name: 'Square mile', symbol: 'mi²', factor: 2589988.110336, offset: 0.0, reciprocal: false),
      Unit(name: 'Marla', symbol: 'marla', factor: 25.2929, offset: 0.0, reciprocal: false),
      Unit(name: 'Kanal', symbol: 'kanal', factor: 505.857, offset: 0.0, reciprocal: false),
      Unit(name: 'Bigha (pucca)', symbol: 'bigha', factor: 2529.2852, offset: 0.0, reciprocal: false),
      Unit(name: 'Cent', symbol: 'cent', factor: 40.4686, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'volume',
    name: 'Volume',
    icon: Icons.local_drink_outlined,
    baseUnitLabel: 'litre',
    units: <Unit>[
      Unit(name: 'Millilitre', symbol: 'mL', factor: 0.001, offset: 0.0, reciprocal: false),
      Unit(name: 'Centilitre', symbol: 'cL', factor: 0.01, offset: 0.0, reciprocal: false),
      Unit(name: 'Litre', symbol: 'L', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Cubic centimetre', symbol: 'cm³', factor: 0.001, offset: 0.0, reciprocal: false),
      Unit(name: 'Cubic metre', symbol: 'm³', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Cubic inch', symbol: 'in³', factor: 0.016387064, offset: 0.0, reciprocal: false),
      Unit(name: 'Cubic foot', symbol: 'ft³', factor: 28.316846592, offset: 0.0, reciprocal: false),
      Unit(name: 'US teaspoon', symbol: 'tsp', factor: 0.00492892159375, offset: 0.0, reciprocal: false),
      Unit(name: 'US tablespoon', symbol: 'tbsp', factor: 0.01478676478125, offset: 0.0, reciprocal: false),
      Unit(name: 'US fluid ounce', symbol: 'fl oz', factor: 0.0295735295625, offset: 0.0, reciprocal: false),
      Unit(name: 'US cup', symbol: 'cup', factor: 0.2365882365, offset: 0.0, reciprocal: false),
      Unit(name: 'US pint', symbol: 'pt', factor: 0.473176473, offset: 0.0, reciprocal: false),
      Unit(name: 'US quart', symbol: 'qt', factor: 0.946352946, offset: 0.0, reciprocal: false),
      Unit(name: 'US gallon', symbol: 'gal', factor: 3.785411784, offset: 0.0, reciprocal: false),
      Unit(name: 'Imperial pint', symbol: 'imp pt', factor: 0.56826125, offset: 0.0, reciprocal: false),
      Unit(name: 'Imperial gallon', symbol: 'imp gal', factor: 4.54609, offset: 0.0, reciprocal: false),
      Unit(name: 'Oil barrel', symbol: 'bbl', factor: 158.987294928, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'speed',
    name: 'Speed',
    icon: Icons.speed,
    baseUnitLabel: 'metre / second',
    units: <Unit>[
      Unit(name: 'Metre / second', symbol: 'm/s', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilometre / hour', symbol: 'km/h', factor: 0.2777777777777778, offset: 0.0, reciprocal: false),
      Unit(name: 'Mile / hour', symbol: 'mph', factor: 0.44704, offset: 0.0, reciprocal: false),
      Unit(name: 'Foot / second', symbol: 'ft/s', factor: 0.3048, offset: 0.0, reciprocal: false),
      Unit(name: 'Knot', symbol: 'kn', factor: 0.5144444444444445, offset: 0.0, reciprocal: false),
      Unit(name: 'Mach (sea level)', symbol: 'Ma', factor: 340.29, offset: 0.0, reciprocal: false),
      Unit(name: 'Speed of light', symbol: 'c', factor: 299792458.0, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'time',
    name: 'Time',
    icon: Icons.schedule,
    baseUnitLabel: 'second',
    units: <Unit>[
      Unit(name: 'Nanosecond', symbol: 'ns', factor: 1e-09, offset: 0.0, reciprocal: false),
      Unit(name: 'Microsecond', symbol: 'µs', factor: 1e-06, offset: 0.0, reciprocal: false),
      Unit(name: 'Millisecond', symbol: 'ms', factor: 0.001, offset: 0.0, reciprocal: false),
      Unit(name: 'Second', symbol: 's', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Minute', symbol: 'min', factor: 60.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Hour', symbol: 'h', factor: 3600.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Day', symbol: 'd', factor: 86400.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Week', symbol: 'wk', factor: 604800.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Month (30 d)', symbol: 'mo', factor: 2592000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Year (365 d)', symbol: 'yr', factor: 31536000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Decade', symbol: 'dec', factor: 315360000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Century', symbol: 'c', factor: 3153600000.0, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'data',
    name: 'Digital Storage',
    icon: Icons.sd_storage_outlined,
    baseUnitLabel: 'byte',
    units: <Unit>[
      Unit(name: 'Bit', symbol: 'b', factor: 0.125, offset: 0.0, reciprocal: false),
      Unit(name: 'Byte', symbol: 'B', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilobit', symbol: 'kb', factor: 125.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilobyte', symbol: 'KB', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kibibyte', symbol: 'KiB', factor: 1024.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Megabit', symbol: 'Mb', factor: 125000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Megabyte', symbol: 'MB', factor: 1000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Mebibyte', symbol: 'MiB', factor: 1048576.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gigabit', symbol: 'Gb', factor: 125000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gigabyte', symbol: 'GB', factor: 1000000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gibibyte', symbol: 'GiB', factor: 1073741824.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Terabyte', symbol: 'TB', factor: 1000000000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Tebibyte', symbol: 'TiB', factor: 1099511627776.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Petabyte', symbol: 'PB', factor: 1000000000000000.0, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'datarate',
    name: 'Data Transfer Rate',
    icon: Icons.network_check,
    baseUnitLabel: 'bit / second',
    units: <Unit>[
      Unit(name: 'Bit / second', symbol: 'bps', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilobit / second', symbol: 'kbps', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Megabit / second', symbol: 'Mbps', factor: 1000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gigabit / second', symbol: 'Gbps', factor: 1000000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Byte / second', symbol: 'B/s', factor: 8.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilobyte / second', symbol: 'KB/s', factor: 8000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Megabyte / second', symbol: 'MB/s', factor: 8000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gigabyte / second', symbol: 'GB/s', factor: 8000000000.0, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'fuel',
    name: 'Fuel Economy',
    icon: Icons.local_gas_station_outlined,
    baseUnitLabel: 'litres / 100 km',
    units: <Unit>[
      Unit(name: 'Litres / 100 km', symbol: 'L/100km', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilometres / litre', symbol: 'km/L', factor: 100.0, offset: 0.0, reciprocal: true),
      Unit(name: 'Miles / gallon (US)', symbol: 'mpg', factor: 235.214583, offset: 0.0, reciprocal: true),
      Unit(name: 'Miles / gallon (UK)', symbol: 'mpg (UK)', factor: 282.480936, offset: 0.0, reciprocal: true),
      Unit(name: 'Miles / litre', symbol: 'mi/L', factor: 160.9344, offset: 0.0, reciprocal: true),
    ],
  ),
  UnitCategory(
    id: 'pressure',
    name: 'Pressure',
    icon: Icons.compress,
    baseUnitLabel: 'pascal',
    units: <Unit>[
      Unit(name: 'Pascal', symbol: 'Pa', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Hectopascal', symbol: 'hPa', factor: 100.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilopascal', symbol: 'kPa', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Megapascal', symbol: 'MPa', factor: 1000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Bar', symbol: 'bar', factor: 100000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Millibar', symbol: 'mbar', factor: 100.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Atmosphere', symbol: 'atm', factor: 101325.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Torr / mmHg', symbol: 'Torr', factor: 133.322368421, offset: 0.0, reciprocal: false),
      Unit(name: 'Inch of mercury', symbol: 'inHg', factor: 3386.388, offset: 0.0, reciprocal: false),
      Unit(name: 'Pound / sq inch', symbol: 'psi', factor: 6894.757293168, offset: 0.0, reciprocal: false),
      Unit(name: 'Kg-force / cm²', symbol: 'kgf/cm²', factor: 98066.5, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'energy',
    name: 'Energy',
    icon: Icons.bolt,
    baseUnitLabel: 'joule',
    units: <Unit>[
      Unit(name: 'Joule', symbol: 'J', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilojoule', symbol: 'kJ', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Calorie', symbol: 'cal', factor: 4.184, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilocalorie', symbol: 'kcal', factor: 4184.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Watt hour', symbol: 'Wh', factor: 3600.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilowatt hour', symbol: 'kWh', factor: 3600000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Electronvolt', symbol: 'eV', factor: 1.602176634e-19, offset: 0.0, reciprocal: false),
      Unit(name: 'British thermal unit', symbol: 'BTU', factor: 1055.05585262, offset: 0.0, reciprocal: false),
      Unit(name: 'Foot-pound', symbol: 'ft·lb', factor: 1.3558179483314003, offset: 0.0, reciprocal: false),
      Unit(name: 'Therm', symbol: 'thm', factor: 105505585.257348, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'power',
    name: 'Power',
    icon: Icons.electric_bolt_outlined,
    baseUnitLabel: 'watt',
    units: <Unit>[
      Unit(name: 'Watt', symbol: 'W', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilowatt', symbol: 'kW', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Megawatt', symbol: 'MW', factor: 1000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Horsepower (metric)', symbol: 'PS', factor: 735.49875, offset: 0.0, reciprocal: false),
      Unit(name: 'Horsepower (mech.)', symbol: 'hp', factor: 745.6998715822702, offset: 0.0, reciprocal: false),
      Unit(name: 'BTU / hour', symbol: 'BTU/h', factor: 0.29307107017222, offset: 0.0, reciprocal: false),
      Unit(name: 'Calorie / second', symbol: 'cal/s', factor: 4.184, offset: 0.0, reciprocal: false),
      Unit(name: 'Foot-pound / second', symbol: 'ft·lb/s', factor: 1.3558179483314003, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'force',
    name: 'Force',
    icon: Icons.open_in_full,
    baseUnitLabel: 'newton',
    units: <Unit>[
      Unit(name: 'Newton', symbol: 'N', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilonewton', symbol: 'kN', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Dyne', symbol: 'dyn', factor: 1e-05, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilogram-force', symbol: 'kgf', factor: 9.80665, offset: 0.0, reciprocal: false),
      Unit(name: 'Pound-force', symbol: 'lbf', factor: 4.4482216152605, offset: 0.0, reciprocal: false),
      Unit(name: 'Poundal', symbol: 'pdl', factor: 0.138254954376, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'torque',
    name: 'Torque',
    icon: Icons.rotate_right,
    baseUnitLabel: 'newton metre',
    units: <Unit>[
      Unit(name: 'Newton metre', symbol: 'N·m', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Newton centimetre', symbol: 'N·cm', factor: 0.01, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilogram-force metre', symbol: 'kgf·m', factor: 9.80665, offset: 0.0, reciprocal: false),
      Unit(name: 'Pound-force foot', symbol: 'lbf·ft', factor: 1.3558179483314003, offset: 0.0, reciprocal: false),
      Unit(name: 'Pound-force inch', symbol: 'lbf·in', factor: 0.1129848290276167, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'angle',
    name: 'Angle',
    icon: Icons.architecture,
    baseUnitLabel: 'degree',
    units: <Unit>[
      Unit(name: 'Degree', symbol: '°', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Radian', symbol: 'rad', factor: 57.29577951308232, offset: 0.0, reciprocal: false),
      Unit(name: 'Gradian', symbol: 'grad', factor: 0.9, offset: 0.0, reciprocal: false),
      Unit(name: 'Minute of arc', symbol: '\'', factor: 0.016666666666666666, offset: 0.0, reciprocal: false),
      Unit(name: 'Second of arc', symbol: '"', factor: 0.0002777777777777778, offset: 0.0, reciprocal: false),
      Unit(name: 'Turn', symbol: 'turn', factor: 360.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Mil (NATO)', symbol: 'mil', factor: 0.05625, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'frequency',
    name: 'Frequency',
    icon: Icons.graphic_eq,
    baseUnitLabel: 'hertz',
    units: <Unit>[
      Unit(name: 'Hertz', symbol: 'Hz', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilohertz', symbol: 'kHz', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Megahertz', symbol: 'MHz', factor: 1000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gigahertz', symbol: 'GHz', factor: 1000000000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Revolutions / minute', symbol: 'rpm', factor: 0.016666666666666666, offset: 0.0, reciprocal: false),
      Unit(name: 'Beats / minute', symbol: 'bpm', factor: 0.016666666666666666, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'density',
    name: 'Density',
    icon: Icons.layers_outlined,
    baseUnitLabel: 'kg / m³',
    units: <Unit>[
      Unit(name: 'Kilogram / m³', symbol: 'kg/m³', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gram / cm³', symbol: 'g/cm³', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Gram / litre', symbol: 'g/L', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Kilogram / litre', symbol: 'kg/L', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Pound / ft³', symbol: 'lb/ft³', factor: 16.018463373960138, offset: 0.0, reciprocal: false),
      Unit(name: 'Pound / in³', symbol: 'lb/in³', factor: 27679.904710203, offset: 0.0, reciprocal: false),
      Unit(name: 'Ounce / gallon (US)', symbol: 'oz/gal', factor: 7.489151707, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'illuminance',
    name: 'Illuminance',
    icon: Icons.light_mode_outlined,
    baseUnitLabel: 'lux',
    units: <Unit>[
      Unit(name: 'Lux', symbol: 'lx', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Foot-candle', symbol: 'fc', factor: 10.763910416709722, offset: 0.0, reciprocal: false),
      Unit(name: 'Phot', symbol: 'ph', factor: 10000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Nox', symbol: 'nox', factor: 0.001, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'cooking',
    name: 'Cooking',
    icon: Icons.restaurant_menu,
    baseUnitLabel: 'millilitre',
    units: <Unit>[
      Unit(name: 'Millilitre', symbol: 'mL', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Litre', symbol: 'L', factor: 1000.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Teaspoon (US)', symbol: 'tsp', factor: 4.92892159375, offset: 0.0, reciprocal: false),
      Unit(name: 'Tablespoon (US)', symbol: 'tbsp', factor: 14.78676478125, offset: 0.0, reciprocal: false),
      Unit(name: 'Cup (US)', symbol: 'cup', factor: 236.5882365, offset: 0.0, reciprocal: false),
      Unit(name: 'Cup (metric)', symbol: 'cup (m)', factor: 250.0, offset: 0.0, reciprocal: false),
      Unit(name: 'Fluid ounce (US)', symbol: 'fl oz', factor: 29.5735295625, offset: 0.0, reciprocal: false),
      Unit(name: 'Pint (US)', symbol: 'pt', factor: 473.176473, offset: 0.0, reciprocal: false),
      Unit(name: 'Quart (US)', symbol: 'qt', factor: 946.352946, offset: 0.0, reciprocal: false),
      Unit(name: 'Gallon (US)', symbol: 'gal', factor: 3785.411784, offset: 0.0, reciprocal: false),
      Unit(name: 'Dessert spoon', symbol: 'dsp', factor: 10.0, offset: 0.0, reciprocal: false),
    ],
  ),
  UnitCategory(
    id: 'shoe',
    name: 'Shoe Size',
    icon: Icons.ice_skating,
    baseUnitLabel: 'foot length (cm)',
    units: <Unit>[
      Unit(name: 'Foot length (cm)', symbol: 'cm', factor: 1.0, offset: 0.0, reciprocal: false),
      Unit(name: 'EU size', symbol: 'EU', factor: 0.6666666666666666, offset: -1.0, reciprocal: false),
      Unit(name: 'UK size (adult)', symbol: 'UK', factor: 0.846667, offset: 19.05, reciprocal: false),
      Unit(name: 'US men', symbol: 'US M', factor: 0.846667, offset: 17.36, reciprocal: false),
      Unit(name: 'US women', symbol: 'US W', factor: 0.846667, offset: 18.63, reciprocal: false),
      Unit(name: 'Japan (cm)', symbol: 'JP', factor: 1.0, offset: 0.0, reciprocal: false),
    ],
  ),
];

