import 'package:flutter/material.dart';

import 'app_palette.dart';

/// Every theme the user can pick from Settings › Select Theme.
///
/// The family is amber / orange as requested — the original app's blue is
/// gone entirely — with both dark and light members so the picker feels
/// complete. Add a new entry here and it appears in the theme screen
/// automatically.
class ThemeCatalog {
  const ThemeCatalog._();

  static const String defaultId = 'amber_night';

  static const List<AppPalette> all = <AppPalette>[
    // ----------------------------------------------------------- dark ----
    AppPalette(
      id: 'amber_night',
      name: 'Amber Night',
      city: 'Default',
      brightness: Brightness.dark,
      primary: Color(0xFFFFB020),
      onPrimary: Color(0xFF1A1206),
      accent: Color(0xFFFF8A3D),
      background: Color(0xFF0E1013),
      surface: Color(0xFF16191F),
      surfaceAlt: Color(0xFF1F242C),
      outline: Color(0xFF2C323C),
      textPrimary: Color(0xFFF2F4F7),
      textSecondary: Color(0xFF9AA3B2),
      keyFace: Color(0xFF1C2027),
      keyFaceAlt: Color(0xFF262C35),
      keyText: Color(0xFFF2F4F7),
      equalsKey: Color(0xFFE5484D),
      up: Color(0xFF3DD68C),
      down: Color(0xFFE5484D),
    ),
    AppPalette(
      id: 'dubai_gold',
      name: 'Desert Gold',
      city: 'Dubai',
      brightness: Brightness.dark,
      primary: Color(0xFFE8C063),
      onPrimary: Color(0xFF241B05),
      accent: Color(0xFFD9A441),
      background: Color(0xFF13110C),
      surface: Color(0xFF1C1913),
      surfaceAlt: Color(0xFF26211A),
      outline: Color(0xFF3A3226),
      textPrimary: Color(0xFFF6F1E4),
      textSecondary: Color(0xFFAFA68F),
      keyFace: Color(0xFF211C15),
      keyFaceAlt: Color(0xFF2C261D),
      keyText: Color(0xFFF6F1E4),
      equalsKey: Color(0xFFC2472F),
      up: Color(0xFF63C08A),
      down: Color(0xFFC2472F),
    ),
    AppPalette(
      id: 'marrakesh_saffron',
      name: 'Saffron Souk',
      city: 'Marrakesh',
      brightness: Brightness.dark,
      primary: Color(0xFFF2A03D),
      onPrimary: Color(0xFF2A1705),
      accent: Color(0xFFE2703A),
      background: Color(0xFF141010),
      surface: Color(0xFF1E1817),
      surfaceAlt: Color(0xFF2A2220),
      outline: Color(0xFF3D322F),
      textPrimary: Color(0xFFF7EFE8),
      textSecondary: Color(0xFFB3A099),
      keyFace: Color(0xFF231B1A),
      keyFaceAlt: Color(0xFF2F2522),
      keyText: Color(0xFFF7EFE8),
      equalsKey: Color(0xFFD1442F),
      up: Color(0xFF4FC08A),
      down: Color(0xFFD1442F),
    ),
    AppPalette(
      id: 'tokyo_tangerine',
      name: 'Neon Tangerine',
      city: 'Tokyo',
      brightness: Brightness.dark,
      primary: Color(0xFFFF7A1A),
      onPrimary: Color(0xFF1A0E03),
      accent: Color(0xFFFFD166),
      background: Color(0xFF0B0D10),
      surface: Color(0xFF13161B),
      surfaceAlt: Color(0xFF1C2026),
      outline: Color(0xFF2A3038),
      textPrimary: Color(0xFFEFF2F6),
      textSecondary: Color(0xFF8E97A5),
      keyFace: Color(0xFF171A20),
      keyFaceAlt: Color(0xFF212630),
      keyText: Color(0xFFEFF2F6),
      equalsKey: Color(0xFFFF4D4D),
      up: Color(0xFF32D583),
      down: Color(0xFFFF4D4D),
    ),
    AppPalette(
      id: 'seoul_sunset',
      name: 'Sunset Coral',
      city: 'Seoul',
      brightness: Brightness.dark,
      primary: Color(0xFFFF6B4A),
      onPrimary: Color(0xFF200A04),
      accent: Color(0xFFFFA36B),
      background: Color(0xFF101013),
      surface: Color(0xFF191A1F),
      surfaceAlt: Color(0xFF232429),
      outline: Color(0xFF32343B),
      textPrimary: Color(0xFFF3F3F6),
      textSecondary: Color(0xFF9A9BA5),
      keyFace: Color(0xFF1D1E23),
      keyFaceAlt: Color(0xFF282A31),
      keyText: Color(0xFFF3F3F6),
      equalsKey: Color(0xFFE23C3C),
      up: Color(0xFF38CF8B),
      down: Color(0xFFE23C3C),
    ),
    AppPalette(
      id: 'oslo_copper',
      name: 'Copper Dawn',
      city: 'Oslo',
      brightness: Brightness.dark,
      primary: Color(0xFFC97B4A),
      onPrimary: Color(0xFF1B0F07),
      accent: Color(0xFFE0A06B),
      background: Color(0xFF0F1113),
      surface: Color(0xFF181B1E),
      surfaceAlt: Color(0xFF212529),
      outline: Color(0xFF2E3338),
      textPrimary: Color(0xFFEDEFF1),
      textSecondary: Color(0xFF959CA3),
      keyFace: Color(0xFF1B1F22),
      keyFaceAlt: Color(0xFF252A2E),
      keyText: Color(0xFFEDEFF1),
      equalsKey: Color(0xFFB8452F),
      up: Color(0xFF52BE8A),
      down: Color(0xFFB8452F),
    ),
    AppPalette(
      id: 'cairo_bronze',
      name: 'Bronze Bazaar',
      city: 'Cairo',
      brightness: Brightness.dark,
      primary: Color(0xFFB8863B),
      onPrimary: Color(0xFF1C1405),
      accent: Color(0xFFD7B36B),
      background: Color(0xFF111110),
      surface: Color(0xFF1A1A18),
      surfaceAlt: Color(0xFF242422),
      outline: Color(0xFF34332F),
      textPrimary: Color(0xFFF0EEE8),
      textSecondary: Color(0xFFA09C90),
      keyFace: Color(0xFF1E1E1B),
      keyFaceAlt: Color(0xFF282824),
      keyText: Color(0xFFF0EEE8),
      equalsKey: Color(0xFFA83F2C),
      up: Color(0xFF5BB683),
      down: Color(0xFFA83F2C),
    ),

    // ---------------------------------------------------------- light ----
    AppPalette(
      id: 'lisbon_terracotta',
      name: 'Terracotta',
      city: 'Lisbon',
      brightness: Brightness.light,
      primary: Color(0xFFC9542B),
      onPrimary: Color(0xFFFFFFFF),
      accent: Color(0xFFE08A3C),
      background: Color(0xFFFFF8F2),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFF6EBE1),
      outline: Color(0xFFE4D3C6),
      textPrimary: Color(0xFF241A14),
      textSecondary: Color(0xFF7C6A5D),
      keyFace: Color(0xFFFFFFFF),
      keyFaceAlt: Color(0xFFF1E4D9),
      keyText: Color(0xFF241A14),
      equalsKey: Color(0xFFC9542B),
      up: Color(0xFF1E9E63),
      down: Color(0xFFC2392C),
    ),
    AppPalette(
      id: 'zurich_honey',
      name: 'Honey Light',
      city: 'Zürich',
      brightness: Brightness.light,
      primary: Color(0xFFE09B12),
      onPrimary: Color(0xFF231600),
      accent: Color(0xFFF5C451),
      background: Color(0xFFFFFCF6),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFF7F1E3),
      outline: Color(0xFFE6DCC6),
      textPrimary: Color(0xFF1F1B12),
      textSecondary: Color(0xFF756E5E),
      keyFace: Color(0xFFFFFFFF),
      keyFaceAlt: Color(0xFFF2EADA),
      keyText: Color(0xFF1F1B12),
      equalsKey: Color(0xFFD9541F),
      up: Color(0xFF1E9E63),
      down: Color(0xFFD03A30),
    ),
    AppPalette(
      id: 'sydney_coral',
      name: 'Coral Bay',
      city: 'Sydney',
      brightness: Brightness.light,
      primary: Color(0xFFF2643D),
      onPrimary: Color(0xFFFFFFFF),
      accent: Color(0xFFFFA26B),
      background: Color(0xFFFFF7F4),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFFCEAE3),
      outline: Color(0xFFF0D8CE),
      textPrimary: Color(0xFF231714),
      textSecondary: Color(0xFF7E6A63),
      keyFace: Color(0xFFFFFFFF),
      keyFaceAlt: Color(0xFFF7E4DB),
      keyText: Color(0xFF231714),
      equalsKey: Color(0xFFE23C3C),
      up: Color(0xFF1E9E63),
      down: Color(0xFFE23C3C),
    ),
  ];

  static AppPalette byId(String? id) {
    return all.firstWhere(
      (AppPalette p) => p.id == id,
      orElse: () => all.first,
    );
  }
}
